import os
import django
from datetime import time

# Set up Django environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'nomado_project.settings')
django.setup()

from hotel_booking.models import Hotel
from transportation.models import Route

def add_comprehensive_hotels():
    hotels_data = [
        # MUMBAI HOTELS
        {
            'name': 'The Taj Mahal Palace Mumbai',
            'description': 'Iconic luxury hotel overlooking the Gateway of India with heritage architecture and world-class amenities.',
            'address': 'Apollo Bunder, Colaba',
            'city': 'Mumbai',
            'state': 'Maharashtra',
            'country': 'India',
            'pincode': '400001',
            'phone': '+91-22-66653366',
            'email': 'info@tajmumbai.com',
            'price_per_night': 25000,
            'cleanliness_rating': 4.9,
            'comfort_rating': 4.8,
            'safety_rating': 4.9,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Grand Hyatt Mumbai',
            'description': 'Contemporary luxury hotel in Bandra Kurla Complex with stunning city views.',
            'address': 'Off Western Express Highway, Santacruz East',
            'city': 'Mumbai',
            'state': 'Maharashtra',
            'country': 'India',
            'pincode': '400055',
            'phone': '+91-22-66761234',
            'email': 'mumbai.grand@hyatt.com',
            'price_per_night': 18000,
            'cleanliness_rating': 4.7,
            'comfort_rating': 4.6,
            'safety_rating': 4.8,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Hotel Marine Plaza',
            'description': 'Business hotel on Marine Drive with sea-facing rooms and modern amenities.',
            'address': '29, Marine Drive',
            'city': 'Mumbai',
            'state': 'Maharashtra',
            'country': 'India',
            'pincode': '400020',
            'phone': '+91-22-22851212',
            'email': 'info@hotelmarineplaza.com',
            'price_per_night': 8500,
            'cleanliness_rating': 4.2,
            'comfort_rating': 4.3,
            'safety_rating': 4.5,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': False, 'gym': True, 'spa': False, 'room_service': True, 'air_conditioning': True,
            'featured': False,
        },
        {
            'name': 'The Oberoi Mumbai',
            'description': 'Luxury hotel with panoramic views of the Arabian Sea and Mumbai skyline.',
            'address': 'Nariman Point',
            'city': 'Mumbai',
            'state': 'Maharashtra',
            'country': 'India',
            'pincode': '400021',
            'phone': '+91-22-66325757',
            'email': 'info@oberoihotels.com',
            'price_per_night': 22000,
            'cleanliness_rating': 4.8,
            'comfort_rating': 4.7,
            'safety_rating': 4.8,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Budget Inn Andheri',
            'description': 'Affordable accommodation near Andheri station with basic amenities.',
            'address': 'Andheri West, Near Metro Station',
            'city': 'Mumbai',
            'state': 'Maharashtra',
            'country': 'India',
            'pincode': '400058',
            'phone': '+91-22-26734567',
            'email': 'info@budgetinnandheri.com',
            'price_per_night': 2800,
            'cleanliness_rating': 3.8,
            'comfort_rating': 3.5,
            'safety_rating': 4.0,
            'wifi': True, 'parking': False, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': False, 'air_conditioning': True,
            'featured': False,
        },
        {
            'name': 'Backpacker Paradise Bandra',
            'description': 'Hip hostel in Bandra with rooftop cafe and social spaces for young travelers.',
            'address': 'Hill Road, Bandra West',
            'city': 'Mumbai',
            'state': 'Maharashtra',
            'country': 'India',
            'pincode': '400050',
            'phone': '+91-22-26431234',
            'email': 'info@backpackerparadise.com',
            'price_per_night': 1500,
            'cleanliness_rating': 3.9,
            'comfort_rating': 3.6,
            'safety_rating': 4.1,
            'wifi': True, 'parking': False, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': False, 'air_conditioning': False,
            'featured': False,
        },

        # DELHI HOTELS (6 hotels)
        {
            'name': 'The Imperial New Delhi',
            'description': 'Heritage luxury hotel in the heart of New Delhi with colonial architecture.',
            'address': 'Janpath, Connaught Place',
            'city': 'Delhi',
            'state': 'Delhi',
            'country': 'India',
            'pincode': '110001',
            'phone': '+91-11-23341234',
            'email': 'info@theimperialindia.com',
            'price_per_night': 22000,
            'cleanliness_rating': 4.8,
            'comfort_rating': 4.7,
            'safety_rating': 4.9,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'The Leela Palace New Delhi',
            'description': 'Ultra-luxury hotel combining traditional Indian hospitality with contemporary elegance.',
            'address': 'Chanakyapuri, Diplomatic Enclave',
            'city': 'Delhi',
            'state': 'Delhi',
            'country': 'India',
            'pincode': '110023',
            'phone': '+91-11-39331234',
            'email': 'info@theleela.com',
            'price_per_night': 28000,
            'cleanliness_rating': 4.9,
            'comfort_rating': 4.8,
            'safety_rating': 4.9,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Radisson Blu Plaza Delhi',
            'description': 'Modern business hotel near Connaught Place with excellent connectivity.',
            'address': 'National Highway 8, Mahipalpur',
            'city': 'Delhi',
            'state': 'Delhi',
            'country': 'India',
            'pincode': '110037',
            'phone': '+91-11-26779191',
            'email': 'info@radissonblu.com',
            'price_per_night': 12000,
            'cleanliness_rating': 4.5,
            'comfort_rating': 4.4,
            'safety_rating': 4.6,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Hotel City Center Karol Bagh',
            'description': 'Mid-range hotel in Karol Bagh shopping district with modern facilities.',
            'address': 'Karol Bagh, Near Metro Station',
            'city': 'Delhi',
            'state': 'Delhi',
            'country': 'India',
            'pincode': '110005',
            'phone': '+91-11-25781234',
            'email': 'info@citycenterdl.com',
            'price_per_night': 6500,
            'cleanliness_rating': 4.1,
            'comfort_rating': 4.0,
            'safety_rating': 4.3,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': True, 'air_conditioning': True,
            'featured': False,
        },
        {
            'name': 'Hotel Ajanta Delhi',
            'description': 'Budget hotel near New Delhi Railway Station with basic amenities.',
            'address': 'Ajmeri Gate Extension',
            'city': 'Delhi',
            'state': 'Delhi',
            'country': 'India',
            'pincode': '110006',
            'phone': '+91-11-23276789',
            'email': 'info@ajantadelhi.com',
            'price_per_night': 3200,
            'cleanliness_rating': 3.7,
            'comfort_rating': 3.5,
            'safety_rating': 3.9,
            'wifi': True, 'parking': False, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': False, 'air_conditioning': True,
            'featured': False,
        },
        {
            'name': 'Backpacker Hostel Paharganj',
            'description': 'Budget accommodation in Paharganj backpacker area near New Delhi Railway Station.',
            'address': 'Main Bazaar, Paharganj',
            'city': 'Delhi',
            'state': 'Delhi',
            'country': 'India',
            'pincode': '110055',
            'phone': '+91-11-23562789',
            'email': 'info@backpackerdl.com',
            'price_per_night': 1200,
            'cleanliness_rating': 3.5,
            'comfort_rating': 3.2,
            'safety_rating': 3.8,
            'wifi': True, 'parking': False, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': False, 'air_conditioning': False,
            'featured': False,
        },

        # BANGALORE HOTELS (6 hotels)
        {
            'name': 'The Leela Palace Bengaluru',
            'description': 'Opulent palace hotel with royal architecture and world-class amenities in the heart of the city.',
            'address': '23, Kodihalli, HAL Airport Road',
            'city': 'Bangalore',
            'state': 'Karnataka',
            'country': 'India',
            'pincode': '560008',
            'phone': '+91-80-25211234',
            'email': 'info@theleela.com',
            'price_per_night': 28000,
            'cleanliness_rating': 4.9,
            'comfort_rating': 4.8,
            'safety_rating': 4.9,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'ITC Windsor Bengaluru',
            'description': 'Luxury heritage hotel with colonial charm and modern amenities in the city center.',
            'address': '25, Golf Course Road, Windsor Square',
            'city': 'Bangalore',
            'state': 'Karnataka',
            'country': 'India',
            'pincode': '560052',
            'phone': '+91-80-22269898',
            'email': 'info@itchotels.in',
            'price_per_night': 15000,
            'cleanliness_rating': 4.6,
            'comfort_rating': 4.5,
            'safety_rating': 4.7,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Sheraton Grand Bengaluru',
            'description': 'Contemporary luxury hotel with state-of-the-art facilities and premium services.',
            'address': '26/1 Dr. Rajkumar Road',
            'city': 'Bangalore',
            'state': 'Karnataka',
            'country': 'India',
            'pincode': '560055',
            'phone': '+91-80-42524000',
            'email': 'info@sheraton.com',
            'price_per_night': 16500,
            'cleanliness_rating': 4.6,
            'comfort_rating': 4.5,
            'safety_rating': 4.7,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Brigade Road Business Hotel',
            'description': 'Convenient business hotel on Brigade Road with shopping and dining nearby.',
            'address': 'Brigade Road, Near Commercial Street',
            'city': 'Bangalore',
            'state': 'Karnataka',
            'country': 'India',
            'pincode': '560025',
            'phone': '+91-80-22871234',
            'email': 'info@brigaderoadhotel.com',
            'price_per_night': 7500,
            'cleanliness_rating': 4.2,
            'comfort_rating': 4.1,
            'safety_rating': 4.4,
            'wifi': True, 'parking': False, 'restaurant': True, 'pool': False, 'gym': True, 'spa': False, 'room_service': True, 'air_conditioning': True,
            'featured': False,
        },
        {
            'name': 'Hotel Nandhana Grand',
            'description': 'Mid-range hotel with comfortable rooms and good amenities near city center.',
            'address': 'Rajajinagar, Near Metro Station',
            'city': 'Bangalore',
            'state': 'Karnataka',
            'country': 'India',
            'pincode': '560010',
            'phone': '+91-80-23451234',
            'email': 'info@nandhana.com',
            'price_per_night': 4800,
            'cleanliness_rating': 4.0,
            'comfort_rating': 3.9,
            'safety_rating': 4.2,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': True, 'air_conditioning': True,
            'featured': False,
        },
        {
            'name': 'Zostel Bangalore',
            'description': 'Modern hostel with co-working spaces and social areas for budget travelers.',
            'address': 'Koramangala, 5th Block',
            'city': 'Bangalore',
            'state': 'Karnataka',
            'country': 'India',
            'pincode': '560095',
            'phone': '+91-80-41234567',
            'email': 'bangalore@zostel.com',
            'price_per_night': 1800,
            'cleanliness_rating': 4.0,
            'comfort_rating': 3.8,
            'safety_rating': 4.2,
            'wifi': True, 'parking': False, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': False, 'air_conditioning': True,
            'featured': False,
        },

        # GOA HOTELS (6 hotels)
        {
            'name': 'Taj Exotica Resort & Spa Goa',
            'description': 'Luxury beachfront resort with pristine beaches and world-class spa facilities.',
            'address': 'Calwaddo, Benaulim',
            'city': 'Goa',
            'state': 'Goa',
            'country': 'India',
            'pincode': '403716',
            'phone': '+91-832-6683333',
            'email': 'info@tajgoa.com',
            'price_per_night': 32000,
            'cleanliness_rating': 4.8,
            'comfort_rating': 4.9,
            'safety_rating': 4.8,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'W Goa',
            'description': 'Trendy beachfront hotel with vibrant nightlife and contemporary design.',
            'address': 'Vagator Beach, Bardez',
            'city': 'Goa',
            'state': 'Goa',
            'country': 'India',
            'pincode': '403509',
            'phone': '+91-832-6716666',
            'email': 'info@wgoa.com',
            'price_per_night': 24000,
            'cleanliness_rating': 4.7,
            'comfort_rating': 4.6,
            'safety_rating': 4.7,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Grand Hyatt Goa',
            'description': 'Luxury resort with expansive grounds, multiple pools, and beachfront access.',
            'address': 'P.O. Goa University, Bambolim',
            'city': 'Goa',
            'state': 'Goa',
            'country': 'India',
            'pincode': '403206',
            'phone': '+91-832-6721234',
            'email': 'info@grandhyattgoa.com',
            'price_per_night': 19500,
            'cleanliness_rating': 4.6,
            'comfort_rating': 4.7,
            'safety_rating': 4.6,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Calangute Beach Resort',
            'description': 'Mid-range beachfront resort with easy access to Calangute Beach and water sports.',
            'address': 'Calangute Beach Road',
            'city': 'Goa',
            'state': 'Goa',
            'country': 'India',
            'pincode': '403516',
            'phone': '+91-832-2276543',
            'email': 'info@calanguteresort.com',
            'price_per_night': 8500,
            'cleanliness_rating': 4.1,
            'comfort_rating': 4.2,
            'safety_rating': 4.3,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': False, 'spa': False, 'room_service': True, 'air_conditioning': True,
            'featured': False,
        },
        {
            'name': 'Panjim Inn Heritage Hotel',
            'description': 'Colonial-era heritage hotel in Old Goa with traditional Portuguese architecture.',
            'address': 'E-212, 31st January Road, Fontainhas',
            'city': 'Goa',
            'state': 'Goa',
            'country': 'India',
            'pincode': '403001',
            'phone': '+91-832-2226523',
            'email': 'info@panjiminn.com',
            'price_per_night': 6200,
            'cleanliness_rating': 4.0,
            'comfort_rating': 4.1,
            'safety_rating': 4.2,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': True, 'air_conditioning': True,
            'featured': False,
        },
        {
            'name': 'Anjuna Beach Hostel',
            'description': 'Backpacker hostel near famous Anjuna Beach with vibrant party scene.',
            'address': 'Anjuna Beach Road',
            'city': 'Goa',
            'state': 'Goa',
            'country': 'India',
            'pincode': '403509',
            'phone': '+91-832-2274321',
            'email': 'info@anjunahostel.com',
            'price_per_night': 2200,
            'cleanliness_rating': 3.8,
            'comfort_rating': 3.6,
            'safety_rating': 3.9,
            'wifi': True, 'parking': False, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': False, 'air_conditioning': True,
            'featured': False,
        },

        # JAIPUR HOTELS (5 hotels)
        {
            'name': 'Rambagh Palace Jaipur',
            'description': 'Former residence of Maharaja, now a luxury palace hotel with royal heritage.',
            'address': 'Bhawani Singh Road',
            'city': 'Jaipur',
            'state': 'Rajasthan',
            'country': 'India',
            'pincode': '302005',
            'phone': '+91-141-2385700',
            'email': 'info@rambaghpalace.com',
            'price_per_night': 35000,
            'cleanliness_rating': 4.9,
            'comfort_rating': 4.8,
            'safety_rating': 4.9,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Fairmont Jaipur',
            'description': 'Luxury resort hotel with Rajasthani architecture and modern amenities.',
            'address': '2, Riico Kukas, Near Mahindra SEZ',
            'city': 'Jaipur',
            'state': 'Rajasthan',
            'country': 'India',
            'pincode': '302028',
            'phone': '+91-141-2673333',
            'email': 'info@fairmont.com',
            'price_per_night': 18000,
            'cleanliness_rating': 4.6,
            'comfort_rating': 4.7,
            'safety_rating': 4.8,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'ITC Rajputana Jaipur',
            'description': 'Luxury hotel blending Rajasthani culture with contemporary comfort.',
            'address': 'Palace Road, Civil Lines',
            'city': 'Jaipur',
            'state': 'Rajasthan',
            'country': 'India',
            'pincode': '302006',
            'phone': '+91-141-5100100',
            'email': 'info@itchotels.in',
            'price_per_night': 14500,
            'cleanliness_rating': 4.5,
            'comfort_rating': 4.4,
            'safety_rating': 4.6,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Hotel Pink City',
            'description': 'Traditional Rajasthani hotel in the heart of Pink City with cultural experiences.',
            'address': 'Near Hawa Mahal, Old City',
            'city': 'Jaipur',
            'state': 'Rajasthan',
            'country': 'India',
            'pincode': '302002',
            'phone': '+91-141-2618901',
            'email': 'info@hotelpinkcity.com',
            'price_per_night': 6800,
            'cleanliness_rating': 4.0,
            'comfort_rating': 4.1,
            'safety_rating': 4.2,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': True, 'air_conditioning': True,
            'featured': False,
        },
        {
            'name': 'Zostel Jaipur',
            'description': 'Vibrant hostel with traditional Rajasthani architecture and modern amenities.',
            'address': 'C-Scheme, Near Jaipur Railway Station',
            'city': 'Jaipur',
            'state': 'Rajasthan',
            'country': 'India',
            'pincode': '302001',
            'phone': '+91-141-4567890',
            'email': 'jaipur@zostel.com',
            'price_per_night': 1600,
            'cleanliness_rating': 4.1,
            'comfort_rating': 3.8,
            'safety_rating': 4.3,
            'wifi': True, 'parking': False, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': False, 'air_conditioning': True,
            'featured': False,
        },

        # KERALA HOTELS (6 hotels)
        {
            'name': 'Kumarakom Lake Resort',
            'description': 'Luxury backwater resort with traditional Kerala architecture and Ayurvedic spa.',
            'address': 'Kumarakom, Kottayam',
            'city': 'Kumarakom',
            'state': 'Kerala',
            'country': 'India',
            'pincode': '686566',
            'phone': '+91-481-2524900',
            'email': 'info@kumarakomlakeresort.com',
            'price_per_night': 22000,
            'cleanliness_rating': 4.7,
            'comfort_rating': 4.8,
            'safety_rating': 4.6,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': False, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Kochi Marriott Hotel',
            'description': 'Waterfront luxury hotel with stunning views of Vembanad Lake.',
            'address': 'Lulu International Shopping Mall, Edapally',
            'city': 'Kochi',
            'state': 'Kerala',
            'country': 'India',
            'pincode': '682024',
            'phone': '+91-484-7177777',
            'email': 'info@marriottkochi.com',
            'price_per_night': 11500,
            'cleanliness_rating': 4.4,
            'comfort_rating': 4.3,
            'safety_rating': 4.5,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': False,
        },
        {
            'name': 'Backwater Hostel Alleppey',
            'description': 'Budget hostel with houseboat experiences and backwater tours.',
            'address': 'Boat Jetty Road, Alleppey',
            'city': 'Alleppey',
            'state': 'Kerala',
            'country': 'India',
            'pincode': '688012',
            'phone': '+91-477-2234567',
            'email': 'info@backwaterhostel.com',
            'price_per_night': 2000,
            'cleanliness_rating': 3.9,
            'comfort_rating': 3.7,
            'safety_rating': 4.0,
            'wifi': True, 'parking': False, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': False, 'air_conditioning': True,
            'featured': False,
        },

        # CHENNAI HOTELS (5 hotels)
        {
            'name': 'The Leela Palace Chennai',
            'description': 'Luxury beachfront hotel with stunning Bay of Bengal views and royal hospitality.',
            'address': 'Adyar Seaface, MRC Nagar',
            'city': 'Chennai',
            'state': 'Tamil Nadu',
            'country': 'India',
            'pincode': '600028',
            'phone': '+91-44-39661234',
            'email': 'info@theleelachennai.com',
            'price_per_night': 26000,
            'cleanliness_rating': 4.8,
            'comfort_rating': 4.7,
            'safety_rating': 4.8,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'ITC Grand Chola Chennai',
            'description': 'Palatial luxury hotel inspired by Chola architecture with world-class amenities.',
            'address': '63, Mount Road, Guindy',
            'city': 'Chennai',
            'state': 'Tamil Nadu',
            'country': 'India',
            'pincode': '600032',
            'phone': '+91-44-22200000',
            'email': 'info@itchotels.in',
            'price_per_night': 20000,
            'cleanliness_rating': 4.7,
            'comfort_rating': 4.6,
            'safety_rating': 4.8,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Hotel Savera Chennai',
            'description': 'Business hotel in the heart of Chennai with easy access to shopping and business districts.',
            'address': '146, Dr Radhakrishnan Salai, Mylapore',
            'city': 'Chennai',
            'state': 'Tamil Nadu',
            'country': 'India',
            'pincode': '600004',
            'phone': '+91-44-28112100',
            'email': 'info@hotelsavera.com',
            'price_per_night': 7200,
            'cleanliness_rating': 4.1,
            'comfort_rating': 4.0,
            'safety_rating': 4.3,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': False, 'gym': True, 'spa': False, 'room_service': True, 'air_conditioning': True,
            'featured': False,
        },
        {
            'name': 'Park Hyatt Chennai',
            'description': 'Contemporary luxury hotel with sophisticated design and premium amenities.',
            'address': '39, Velachery Main Road, Guindy',
            'city': 'Chennai',
            'state': 'Tamil Nadu',
            'country': 'India',
            'pincode': '600032',
            'phone': '+91-44-71771234',
            'email': 'info@hyatt.com',
            'price_per_night': 16500,
            'cleanliness_rating': 4.6,
            'comfort_rating': 4.5,
            'safety_rating': 4.7,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Budget Stay T Nagar',
            'description': 'Affordable accommodation in the shopping hub of T Nagar.',
            'address': 'Ranganathan Street, T Nagar',
            'city': 'Chennai',
            'state': 'Tamil Nadu',
            'country': 'India',
            'pincode': '600017',
            'phone': '+91-44-24343456',
            'email': 'info@budgettnagar.com',
            'price_per_night': 3200,
            'cleanliness_rating': 3.8,
            'comfort_rating': 3.6,
            'safety_rating': 4.0,
            'wifi': True, 'parking': False, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': False, 'air_conditioning': True,
            'featured': False,
        },

        # HYDERABAD HOTELS (5 hotels)
        {
            'name': 'Taj Falaknuma Palace',
            'description': 'Opulent palace hotel perched on a hilltop with panoramic city views and royal heritage.',
            'address': 'Engine Bowli, Falaknuma',
            'city': 'Hyderabad',
            'state': 'Telangana',
            'country': 'India',
            'pincode': '500053',
            'phone': '+91-40-66293333',
            'email': 'info@tajfalaknuma.com',
            'price_per_night': 38000,
            'cleanliness_rating': 4.9,
            'comfort_rating': 4.8,
            'safety_rating': 4.9,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Park Hyatt Hyderabad',
            'description': 'Contemporary luxury hotel in HITEC City with modern amenities and business facilities.',
            'address': 'Road No 2, Banjara Hills',
            'city': 'Hyderabad',
            'state': 'Telangana',
            'country': 'India',
            'pincode': '500034',
            'phone': '+91-40-49341234',
            'email': 'info@hyatt.com',
            'price_per_night': 16000,
            'cleanliness_rating': 4.6,
            'comfort_rating': 4.5,
            'safety_rating': 4.7,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Novotel Hyderabad Airport',
            'description': 'Modern airport hotel with convenient location and excellent facilities.',
            'address': 'GMR Hyderabad International Airport',
            'city': 'Hyderabad',
            'state': 'Telangana',
            'country': 'India',
            'pincode': '500409',
            'phone': '+91-40-67135500',
            'email': 'info@novotel.com',
            'price_per_night': 9500,
            'cleanliness_rating': 4.3,
            'comfort_rating': 4.2,
            'safety_rating': 4.5,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': False, 'room_service': True, 'air_conditioning': True,
            'featured': False,
        },
        {
            'name': 'Minerva Grand Hyderabad',
            'description': 'Business hotel near Secunderabad Railway Station with comfortable accommodation.',
            'address': 'S.D. Road, Secunderabad',
            'city': 'Hyderabad',
            'state': 'Telangana',
            'country': 'India',
            'pincode': '500003',
            'phone': '+91-40-27806666',
            'email': 'info@minervagrand.com',
            'price_per_night': 5800,
            'cleanliness_rating': 4.0,
            'comfort_rating': 3.9,
            'safety_rating': 4.2,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': True, 'air_conditioning': True,
            'featured': False,
        },
        {
            'name': 'Treebo Trend Hyderabad',
            'description': 'Modern budget hotel with standardized amenities and good service.',
            'address': 'Ameerpet, Near Metro Station',
            'city': 'Hyderabad',
            'state': 'Telangana',
            'country': 'India',
            'pincode': '500016',
            'phone': '+91-40-40123456',
            'email': 'info@treebo.com',
            'price_per_night': 2800,
            'cleanliness_rating': 4.0,
            'comfort_rating': 3.8,
            'safety_rating': 4.1,
            'wifi': True, 'parking': False, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': False, 'air_conditioning': True,
            'featured': False,
        },

        # PUNE HOTELS (5 hotels)
        {
            'name': 'The Westin Pune Koregaon Park',
            'description': 'Luxury hotel in the heart of Pune with contemporary design and premium amenities.',
            'address': '36/3-B, Koregaon Park Annexe',
            'city': 'Pune',
            'state': 'Maharashtra',
            'country': 'India',
            'pincode': '411001',
            'phone': '+91-20-67721000',
            'email': 'info@westin.com',
            'price_per_night': 14000,
            'cleanliness_rating': 4.6,
            'comfort_rating': 4.5,
            'safety_rating': 4.7,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Conrad Pune',
            'description': 'Modern luxury hotel with sophisticated design and world-class facilities.',
            'address': '7, MG Road',
            'city': 'Pune',
            'state': 'Maharashtra',
            'country': 'India',
            'pincode': '411001',
            'phone': '+91-20-67171000',
            'email': 'info@conrad.com',
            'price_per_night': 12500,
            'cleanliness_rating': 4.5,
            'comfort_rating': 4.4,
            'safety_rating': 4.6,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'JW Marriott Pune',
            'description': 'Luxury hotel with elegant design and comprehensive business facilities.',
            'address': 'Senapati Bapat Road',
            'city': 'Pune',
            'state': 'Maharashtra',
            'country': 'India',
            'pincode': '411053',
            'phone': '+91-20-66813000',
            'email': 'info@marriott.com',
            'price_per_night': 13500,
            'cleanliness_rating': 4.5,
            'comfort_rating': 4.4,
            'safety_rating': 4.6,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Hotel Sunderban Pune',
            'description': 'Mid-range hotel near Pune Junction with convenient location and good amenities.',
            'address': 'Sassoon Road, Near Railway Station',
            'city': 'Pune',
            'state': 'Maharashtra',
            'country': 'India',
            'pincode': '411001',
            'phone': '+91-20-26129600',
            'email': 'info@hotelsunderban.com',
            'price_per_night': 4500,
            'cleanliness_rating': 4.0,
            'comfort_rating': 3.8,
            'safety_rating': 4.1,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': True, 'air_conditioning': True,
            'featured': False,
        },
        {
            'name': 'Zostel Pune',
            'description': 'Vibrant hostel with modern amenities and social spaces for travelers.',
            'address': 'Koregaon Park, Near Osho Ashram',
            'city': 'Pune',
            'state': 'Maharashtra',
            'country': 'India',
            'pincode': '411001',
            'phone': '+91-20-26567890',
            'email': 'pune@zostel.com',
            'price_per_night': 1400,
            'cleanliness_rating': 4.2,
            'comfort_rating': 3.9,
            'safety_rating': 4.3,
            'wifi': True, 'parking': False, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': False, 'air_conditioning': True,
            'featured': False,
        },

        # KOLKATA HOTELS (5 hotels)
        {
            'name': 'The Oberoi Grand Kolkata',
            'description': 'Historic luxury hotel in the heart of Kolkata with colonial elegance.',
            'address': '15, Jawaharlal Nehru Road',
            'city': 'Kolkata',
            'state': 'West Bengal',
            'country': 'India',
            'pincode': '700013',
            'phone': '+91-33-22492323',
            'email': 'info@oberoihotels.com',
            'price_per_night': 18000,
            'cleanliness_rating': 4.7,
            'comfort_rating': 4.6,
            'safety_rating': 4.8,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'ITC Sonar Kolkata',
            'description': 'Luxury hotel with contemporary design and world-class amenities.',
            'address': 'JBS Haldane Avenue, IT Sector-V',
            'city': 'Kolkata',
            'state': 'West Bengal',
            'country': 'India',
            'pincode': '700046',
            'phone': '+91-33-23454545',
            'email': 'info@itchotels.in',
            'price_per_night': 15000,
            'cleanliness_rating': 4.6,
            'comfort_rating': 4.5,
            'safety_rating': 4.7,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Hotel Hindusthan International',
            'description': 'Heritage hotel with old-world charm and modern comforts.',
            'address': '235/1, AJC Bose Road',
            'city': 'Kolkata',
            'state': 'West Bengal',
            'country': 'India',
            'pincode': '700020',
            'phone': '+91-33-22470394',
            'email': 'info@hhi.co.in',
            'price_per_night': 6800,
            'cleanliness_rating': 4.1,
            'comfort_rating': 4.0,
            'safety_rating': 4.2,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': False, 'gym': True, 'spa': False, 'room_service': True, 'air_conditioning': True,
            'featured': False,
        },
        {
            'name': 'Park Street Hotel',
            'description': 'Boutique hotel on famous Park Street with vibrant nightlife nearby.',
            'address': '17, Park Street',
            'city': 'Kolkata',
            'state': 'West Bengal',
            'country': 'India',
            'pincode': '700016',
            'phone': '+91-33-22292929',
            'email': 'info@parkstreethotel.com',
            'price_per_night': 5200,
            'cleanliness_rating': 4.0,
            'comfort_rating': 3.9,
            'safety_rating': 4.1,
            'wifi': True, 'parking': False, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': True, 'air_conditioning': True,
            'featured': False,
        },
        {
            'name': 'Backpacker Panda Kolkata',
            'description': 'Budget hostel with cultural tours and local experiences.',
            'address': 'Sudder Street, Near New Market',
            'city': 'Kolkata',
            'state': 'West Bengal',
            'country': 'India',
            'pincode': '700016',
            'phone': '+91-33-22525678',
            'email': 'kolkata@backpackerpanda.com',
            'price_per_night': 1100,
            'cleanliness_rating': 3.8,
            'comfort_rating': 3.5,
            'safety_rating': 3.9,
            'wifi': True, 'parking': False, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': False, 'air_conditioning': False,
            'featured': False,
        },

        # AGRA HOTELS (4 hotels)
        {
            'name': 'The Oberoi Amarvilas Agra',
            'description': 'Luxury hotel with uninterrupted views of the Taj Mahal from all rooms.',
            'address': 'Taj East Gate Road',
            'city': 'Agra',
            'state': 'Uttar Pradesh',
            'country': 'India',
            'pincode': '282001',
            'phone': '+91-562-2231515',
            'email': 'info@oberoihotels.com',
            'price_per_night': 45000,
            'cleanliness_rating': 4.9,
            'comfort_rating': 4.9,
            'safety_rating': 4.9,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'ITC Mughal Agra',
            'description': 'Luxury resort hotel inspired by Mughal architecture with extensive gardens.',
            'address': 'Taj Ganj, Fatehabad Road',
            'city': 'Agra',
            'state': 'Uttar Pradesh',
            'country': 'India',
            'pincode': '282001',
            'phone': '+91-562-4026000',
            'email': 'info@itchotels.in',
            'price_per_night': 19500,
            'cleanliness_rating': 4.6,
            'comfort_rating': 4.5,
            'safety_rating': 4.7,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Hotel Taj Plaza Agra',
            'description': 'Heritage hotel near Taj Mahal with traditional Mughal architecture.',
            'address': 'Taj East Gate Road, Taj Ganj',
            'city': 'Agra',
            'state': 'Uttar Pradesh',
            'country': 'India',
            'pincode': '282001',
            'phone': '+91-562-2330188',
            'email': 'info@tajplaza.com',
            'price_per_night': 7500,
            'cleanliness_rating': 4.2,
            'comfort_rating': 4.1,
            'safety_rating': 4.3,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': True, 'air_conditioning': True,
            'featured': False,
        },
        {
            'name': 'Backpacker Inn Agra',
            'description': 'Budget accommodation with rooftop views of Taj Mahal.',
            'address': 'Taj Ganj, Near South Gate',
            'city': 'Agra',
            'state': 'Uttar Pradesh',
            'country': 'India',
            'pincode': '282001',
            'phone': '+91-562-2331234',
            'email': 'info@backpackeragra.com',
            'price_per_night': 1800,
            'cleanliness_rating': 3.9,
            'comfort_rating': 3.7,
            'safety_rating': 4.0,
            'wifi': True, 'parking': False, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': False, 'air_conditioning': True,
            'featured': False,
        },

        # UDAIPUR HOTELS (4 hotels)
        {
            'name': 'The Oberoi Udaivilas',
            'description': 'Palace hotel on Lake Pichola with stunning architecture and royal heritage.',
            'address': 'Haridasji Ki Magri',
            'city': 'Udaipur',
            'state': 'Rajasthan',
            'country': 'India',
            'pincode': '313001',
            'phone': '+91-294-2433300',
            'email': 'info@oberoihotels.com',
            'price_per_night': 42000,
            'cleanliness_rating': 4.9,
            'comfort_rating': 4.8,
            'safety_rating': 4.9,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Taj Lake Palace Udaipur',
            'description': 'Iconic white marble palace floating on Lake Pichola.',
            'address': 'Lake Pichola',
            'city': 'Udaipur',
            'state': 'Rajasthan',
            'country': 'India',
            'pincode': '313001',
            'phone': '+91-294-2428800',
            'email': 'info@tajhotels.com',
            'price_per_night': 55000,
            'cleanliness_rating': 4.9,
            'comfort_rating': 4.9,
            'safety_rating': 4.8,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Hotel Lakend Udaipur',
            'description': 'Heritage hotel with lake views and traditional Rajasthani architecture.',
            'address': 'Opposite Nehru Park, Fateh Sagar Lake',
            'city': 'Udaipur',
            'state': 'Rajasthan',
            'country': 'India',
            'pincode': '313001',
            'phone': '+91-294-2431567',
            'email': 'info@hotellakend.com',
            'price_per_night': 8500,
            'cleanliness_rating': 4.3,
            'comfort_rating': 4.2,
            'safety_rating': 4.4,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': False, 'spa': False, 'room_service': True, 'air_conditioning': True,
            'featured': False,
        },
        {
            'name': 'Zostel Udaipur',
            'description': 'Lakeside hostel with cultural activities and budget accommodation.',
            'address': 'Near Fateh Sagar Lake',
            'city': 'Udaipur',
            'state': 'Rajasthan',
            'country': 'India',
            'pincode': '313001',
            'phone': '+91-294-2456789',
            'email': 'udaipur@zostel.com',
            'price_per_night': 1700,
            'cleanliness_rating': 4.1,
            'comfort_rating': 3.9,
            'safety_rating': 4.2,
            'wifi': True, 'parking': False, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': False, 'air_conditioning': True,
            'featured': False,
        },

        # VARANASI HOTELS (3 hotels)
        {
            'name': 'Taj Ganges Varanasi',
            'description': 'Riverside luxury hotel overlooking the sacred Ganges River.',
            'address': 'Nadesar Palace Grounds',
            'city': 'Varanasi',
            'state': 'Uttar Pradesh',
            'country': 'India',
            'pincode': '221002',
            'phone': '+91-542-6613000',
            'email': 'info@tajhotels.com',
            'price_per_night': 24000,
            'cleanliness_rating': 4.7,
            'comfort_rating': 4.6,
            'safety_rating': 4.8,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Hotel Ganges Grand',
            'description': 'Heritage hotel near the ghats with traditional architecture.',
            'address': 'C 1/37, Meer Ghat',
            'city': 'Varanasi',
            'state': 'Uttar Pradesh',
            'country': 'India',
            'pincode': '221001',
            'phone': '+91-542-2450085',
            'email': 'info@gangesgrand.com',
            'price_per_night': 6200,
            'cleanliness_rating': 4.1,
            'comfort_rating': 4.0,
            'safety_rating': 4.2,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': False, 'gym': False, 'spa': False, 'room_service': True, 'air_conditioning': True,
            'featured': False,
        },
        {
            'name': 'Sahi River View Guest House',
            'description': 'Budget guesthouse with Ganges views and spiritual atmosphere.',
            'address': 'D 3/24, Shivala Ghat',
            'city': 'Varanasi',
            'state': 'Uttar Pradesh',
            'country': 'India',
            'pincode': '221001',
            'phone': '+91-542-2393456',
            'email': 'info@sahiguesthouse.com',
            'price_per_night': 2200,
            'cleanliness_rating': 3.8,
            'comfort_rating': 3.6,
            'safety_rating': 3, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Vivanta Trivandrum',
            'description': 'Modern luxury hotel in Thiruvananthapuram with contemporary amenities.',
            'address': 'Kowdiar Palace Road',
            'city': 'Thiruvananthapuram',
            'state': 'Kerala',
            'country': 'India',
            'pincode': '695003',
            'phone': '+91-471-6633633',
            'email': 'info@vivanta.com',
            'price_per_night': 12000,
            'cleanliness_rating': 4.5,
            'comfort_rating': 4.4,
            'safety_rating': 4.6,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': True, 'gym': True, 'spa': True, 'room_service': True, 'air_conditioning': True,
            'featured': True,
        },
        {
            'name': 'Munnar Tea Garden Resort',
            'description': 'Hill station resort surrounded by tea plantations with scenic mountain views.',
            'address': 'Kannan Devan Hills, Munnar',
            'city': 'Munnar',
            'state': 'Kerala',
            'country': 'India',
            'pincode': '685612',
            'phone': '+91-4865-230789',
            'email': 'info@munnartearesort.com',
            'price_per_night': 9500,
            'cleanliness_rating': 4.3,
            'comfort_rating': 4.4,
            'safety_rating': 4.5,
            'wifi': True, 'parking': True, 'restaurant': True, 'pool': False, 'gym': False, 'spa': True, 'room_service': True, 'air_conditioning': False,
            'featured': False,
        }
    ]
    
    for hotel_data in hotels_data:
        hotel, created = Hotel.objects.get_or_create(
            name=hotel_data['name'],
            defaults=hotel_data
        )
        if created:
            print(f"Created hotel: {hotel.name}")
        else:
            print(f"Hotel already exists: {hotel.name}")

def add_comprehensive_routes():
    routes_data = [
        # FLIGHTS - Major Routes
        {
            'transport_type': 'FLIGHT',
            'operator_name': 'Air India',
            'route_number': 'AI-131',
            'source_city': 'Delhi',
            'source_station': 'Indira Gandhi International Airport (DEL)',
            'destination_city': 'Goa',
            'destination_station': 'Goa Airport (GOI)',
            'departure_time': time(14, 20),
            'arrival_time': time(16, 50),
            'duration_hours': 2,
            'duration_minutes': 30,
            'base_price': 8200,
            'total_seats': 150,
            'available_seats': 32,
            'ac_available': True,
            'wifi_available': True,
            'food_service': True,
        },
        {
            'transport_type': 'FLIGHT',
            'operator_name': 'SpiceJet',
            'route_number': 'SG-8709',
            'source_city': 'Mumbai',
            'source_station': 'Chhatrapati Shivaji International Airport (BOM)',
            'destination_city': 'Bangalore',
            'destination_station': 'Kempegowda International Airport (BLR)',
            'departure_time': time(11, 15),
            'arrival_time': time(12, 45),
            'duration_hours': 1,
            'duration_minutes': 30,
            'base_price': 4500,
            'total_seats': 186,
            'available_seats': 67,
            'ac_available': True,
            'wifi_available': False,
            'food_service': True,
        },
        {
            'transport_type': 'FLIGHT',
            'operator_name': 'Vistara',
            'route_number': 'UK-995',
            'source_city': 'Delhi',
            'source_station': 'Indira Gandhi International Airport (DEL)',
            'destination_city': 'Chennai',
            'destination_station': 'Chennai International Airport (MAA)',
            'departure_time': time(19, 30),
            'arrival_time': time(22, 15),
            'duration_hours': 2,
            'duration_minutes': 45,
            'base_price': 7800,
            'total_seats': 164,
            'available_seats': 28,
            'ac_available': True,
            'wifi_available': True,
            'food_service': True,
        },
        {
            'transport_type': 'FLIGHT',
            'operator_name': 'IndiGo',
            'route_number': '6E-6237',
            'source_city': 'Bangalore',
            'source_station': 'Kempegowda International Airport (BLR)',
            'destination_city': 'Hyderabad',
            'destination_station': 'Rajiv Gandhi International Airport (HYD)',
            'departure_time': time(7, 45),
            'arrival_time': time(8, 45),
            'duration_hours': 1,
            'duration_minutes': 0,
            'base_price': 3200,
            'total_seats': 180,
            'available_seats': 89,
            'ac_available': True,
            'wifi_available': True,
            'food_service': False,
        },
        {
            'transport_type': 'FLIGHT',
            'operator_name': 'Air India Express',
            'route_number': 'IX-348',
            'source_city': 'Mumbai',
            'source_station': 'Chhatrapati Shivaji International Airport (BOM)',
            'destination_city': 'Pune',
            'destination_station': 'Pune Airport (PNQ)',
            'departure_time': time(16, 10),
            'arrival_time': time(17, 0),
            'duration_hours': 0,
            'duration_minutes': 50,
            'base_price': 2800,
            'total_seats': 174,
            'available_seats': 45,
            'ac_available': True,
            'wifi_available': False,
            'food_service': False,
        },
        {
            'transport_type': 'FLIGHT',
            'operator_name': 'Go First',
            'route_number': 'G8-315',
            'source_city': 'Jaipur',
            'source_station': 'Jaipur International Airport (JAI)',
            'destination_city': 'Mumbai',
            'destination_station': 'Chhatrapati Shivaji International Airport (BOM)',
            'departure_time': time(13, 25),
            'arrival_time': time(15, 10),
            'duration_hours': 1,
            'duration_minutes': 45,
            'base_price': 5800,
            'total_seats': 180,
            'available_seats': 23,
            'ac_available': True,
            'wifi_available': False,
            'food_service': True,
        },

        # TRAINS - Premium Express Trains
        {
            'transport_type': 'TRAIN',
            'operator_name': 'Indian Railways',
            'route_number': '12951 - Mumbai Rajdhani',
            'source_city': 'Mumbai',
            'source_station': 'Mumbai Central (MMCT)',
            'destination_city': 'Delhi',
            'destination_station': 'New Delhi Railway Station (NDLS)',
            'departure_time': time(16, 25),
            'arrival_time': time(8, 35),
            'duration_hours': 16,
            'duration_minutes': 10,
            'base_price': 2500,
            'total_seats': 400,
            'available_seats': 125,
            'ac_available': True,
            'sleeper_available': True,
            'wifi_available': False,
            'food_service': True,
        },
        {
            'transport_type': 'TRAIN',
            'operator_name': 'Indian Railways',
            'route_number': '12009 - Shatabdi Express',
            'source_city': 'Mumbai',
            'source_station': 'Dadar Central (DR)',
            'destination_city': 'Ahmedabad',
            'destination_station': 'Ahmedabad Junction (ADI)',
            'departure_time': time(21, 40),
            'arrival_time': time(6, 55),
            'duration_hours': 9,
            'duration_minutes': 15,
            'base_price': 1800,
            'total_seats': 350,
            'available_seats': 89,
            'ac_available': True,
            'sleeper_available': True,
            'wifi_available': False,
            'food_service': True,
        },
        {
            'transport_type': 'TRAIN',
            'operator_name': 'Indian Railways',
            'route_number': '12625 - Kerala Express',
            'source_city': 'Delhi',
            'source_station': 'New Delhi Railway Station (NDLS)',
            'destination_city': 'Thiruvananthapuram',
            'destination_station': 'Trivandrum Central (TVC)',
            'departure_time': time(11, 45),
            'arrival_time': time(19, 15),
            'duration_hours': 31,
            'duration_minutes': 30,
            'base_price': 1950,
            'total_seats': 600,
            'available_seats': 178,
            'ac_available': True,
            'sleeper_available': True,
            'wifi_available': False,
            'food_service': True,
        },
        {
            'transport_type': 'TRAIN',
            'operator_name': 'Indian Railways',
            'route_number': '12301 - Howrah Rajdhani',
            'source_city': 'Delhi',
            'source_station': 'New Delhi Railway Station (NDLS)',
            'destination_city': 'Kolkata',
            'destination_station': 'Howrah Junction (HWH)',
            'departure_time': time(17, 0),
            'arrival_time': time(10, 5),
            'duration_hours': 17,
            'duration_minutes': 5,
            'base_price': 2200,
            'total_seats': 450,
            'available_seats': 92,
            'ac_available': True,
            'sleeper_available': True,
            'wifi_available': False,
            'food_service': True,
        },
        {
            'transport_type': 'TRAIN',
            'operator_name': 'Indian Railways',
            'route_number': '12650 - Karnataka Express',
            'source_city': 'Delhi',
            'source_station': 'New Delhi Railway Station (NDLS)',
            'destination_city': 'Bangalore',
            'destination_station': 'Bangalore City Junction (SBC)',
            'departure_time': time(21, 55),
            'arrival_time': time(6, 40),
            'duration_hours': 32,
            'duration_minutes': 45,
            'base_price': 1750,
            'total_seats': 550,
            'available_seats': 203,
            'ac_available': True,
            'sleeper_available': True,
            'wifi_available': False,
            'food_service': True,
        },
        {
            'transport_type': 'TRAIN',
            'operator_name': 'Indian Railways',
            'route_number': '12621 - Tamil Nadu Express',
            'source_city': 'Delhi',
            'source_station': 'New Delhi Railway Station (NDLS)',
            'destination_city': 'Chennai',
            'destination_station': 'Chennai Central (MAS)',
            'departure_time': time(22, 30),
            'arrival_time': time(7, 40),
            'duration_hours': 33,
            'duration_minutes': 10,
            'base_price': 1850,
            'total_seats': 500,
            'available_seats': 145,
            'ac_available': True,
            'sleeper_available': True,
            'wifi_available': False,
            'food_service': True,
        },

        # BUSES - Luxury and Semi-Luxury
        {
            'transport_type': 'BUS',
            'operator_name': 'Volvo Travels',
            'route_number': 'VT-1205',
            'source_city': 'Bangalore',
            'source_station': 'Majestic Bus Stand',
            'destination_city': 'Chennai',
            'destination_station': 'CMBT Bus Stand',
            'departure_time': time(22, 30),
            'arrival_time': time(5, 30),
            'duration_hours': 7,
            'duration_minutes': 0,
            'base_price': 1200,
            'total_seats': 45,
            'available_seats': 18,
            'ac_available': True,
            'sleeper_available': True,
            'wifi_available': True,
            'food_service': False,
        },
        {
            'transport_type': 'BUS',
            'operator_name': 'RedBus Express',
            'route_number': 'RB-456',
            'source_city': 'Pune',
            'source_station': 'Pune Station Bus Stand',
            'destination_city': 'Mumbai',
            'destination_station': 'Dadar Bus Depot',
            'departure_time': time(6, 15),
            'arrival_time': time(9, 45),
            'duration_hours': 3,
            'duration_minutes': 30,
            'base_price': 450,
            'total_seats': 40,
            'available_seats': 22,
            'ac_available': True,
            'sleeper_available': False,
            'wifi_available': True,
            'food_service': False,
        },
        {
            'transport_type': 'BUS',
            'operator_name': 'Sharma Travels',
            'route_number': 'ST-789',
            'source_city': 'Delhi',
            'source_station': 'Kashmere Gate ISBT',
            'destination_city': 'Jaipur',
            'destination_station': 'Sindhi Camp Bus Stand',
            'departure_time': time(23, 0),
            'arrival_time': time(5, 30),
            'duration_hours': 6,
            'duration_minutes': 30,
            'base_price': 800,
            'total_seats': 43,
            'available_seats': 15,
            'ac_available': True,
            'sleeper_available': True,
            'wifi_available': False,
            'food_service': False,
        },
        {
            'transport_type': 'BUS',
            'operator_name': 'Kallada Travels',
            'route_number': 'KT-101',
            'source_city': 'Bangalore',
            'source_station': 'Electronic City',
            'destination_city': 'Thiruvananthapuram',
            'destination_station': 'Thampanoor Bus Station',
            'departure_time': time(20, 0),
            'arrival_time': time(8, 30),
            'duration_hours': 12,
            'duration_minutes': 30,
            'base_price': 1800,
            'total_seats': 40,
            'available_seats': 12,
            'ac_available': True,
            'sleeper_available': True,
            'wifi_available': True,
            'food_service': True,
        },
        {
            'transport_type': 'BUS',
            'operator_name': 'Orange Travels',
            'route_number': 'OT-245',
            'source_city': 'Hyderabad',
            'source_station': 'Jubilee Bus Station',
            'destination_city': 'Bangalore',
            'destination_station': 'Majestic Bus Stand',
            'departure_time': time(21, 45),
            'arrival_time': time(6, 15),
            'duration_hours': 8,
            'duration_minutes': 30,
            'base_price': 1100,
            'total_seats': 42,
            'available_seats': 19,
            'ac_available': True,
            'sleeper_available': True,
            'wifi_available': True,
            'food_service': False,
        },
        {
            'transport_type': 'BUS',
            'operator_name': 'SRS Travels',
            'route_number': 'SRS-567',
            'source_city': 'Chennai',
            'source_station': 'CMBT Bus Stand',
            'destination_city': 'Bangalore',
            'destination_station': 'Satellite Bus Stand',
            'departure_time': time(23, 30),
            'arrival_time': time(6, 0),
            'duration_hours': 6,
            'duration_minutes': 30,
            'base_price': 950,
            'total_seats': 45,
            'available_seats': 25,
            'ac_available': True,
            'sleeper_available': True,
            'wifi_available': False,
            'food_service': False,
        },
        
        {
            'transport_type': 'BUS',
            'operator_name': 'Parveen Travels',
            'route_number': 'PT-890',
            'source_city': 'Mumbai',
            'source_station': 'Mumbai Central Depot',
            'destination_city': 'Goa',
            'destination_station': 'Panaji Kadamba Bus Stand',
            'departure_time': time(19, 30),
            'arrival_time': time(8, 0),
            'duration_hours': 12,
            'duration_minutes': 30,
            'base_price': 1500,
            'total_seats': 40,
            'available_seats': 8,
            'ac_available': True,
            'sleeper_available': True,
            'wifi_available': True,
            'food_service': True,
        },

        # Additional Budget Options
        {
            'transport_type': 'BUS',
            'operator_name': 'MSRTC',
            'route_number': 'MSRTC-234',
            'source_city': 'Mumbai',
            'source_station': 'Dadar Central',
            'destination_city': 'Pune',
            'destination_station': 'Shivajinagar Bus Stand',
            'departure_time': time(7, 0),
            'arrival_time': time(10, 30),
            'duration_hours': 3,
            'duration_minutes': 30,
            'base_price': 350,
            'total_seats': 50,
            'available_seats': 32,
            'ac_available': False,
            'sleeper_available': False,
            'wifi_available': False,
            'food_service': False,
        },
        {
            'transport_type': 'BUS',
            'operator_name': 'KSRTC',
            'route_number': 'KSRTC-456',
            'source_city': 'Bangalore',
            'source_station': 'City Bus Stand',
            'destination_city': 'Munnar',
            'destination_station': 'Munnar Bus Stand',
            'departure_time': time(22, 0),
            'arrival_time': time(6, 30),
            'duration_hours': 8,
            'duration_minutes': 30,
            'base_price': 750,
            'total_seats': 45,
            'available_seats': 28,
            'ac_available': False,
            'sleeper_available': True,
            'wifi_available': False,
            'food_service': False,
        },
        {
            'transport_type': 'TRAIN',
            'operator_name': 'Indian Railways',
            'route_number': '16382 - Kanyakumari Express',
            'source_city': 'Mumbai',
            'source_station': 'Lokmanya Tilak Terminus (LTT)',
            'destination_city': 'Thiruvananthapuram',
            'destination_station': 'Trivandrum Central (TVC)',
            'departure_time': time(5, 15),
            'arrival_time': time(12, 30),
            'duration_hours': 31,
            'duration_minutes': 15,
            'base_price': 1650,
            'total_seats': 500,
            'available_seats': 167,
            'ac_available': True,
            'sleeper_available': True,
            'wifi_available': False,
            'food_service': True,
        },
    ]
    
    for route_data in routes_data:
        route, created = Route.objects.get_or_create(
            route_number=route_data['route_number'],
            defaults=route_data
        )
        if created:
            print(f"Created route: {route.route_number} - {route.source_city} to {route.destination_city}")
        else:
            print(f"Route already exists: {route.route_number}")

if __name__ == "__main__":
    print("Adding comprehensive hotel data...")
    add_comprehensive_hotels()
    
    print("\nAdding comprehensive route data...")
    add_comprehensive_routes()
    
    print("\nComprehensive sample data added successfully!")