# Generated by Django 5.2.6 on 2025-09-09 11:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('FLIGHT', 'Flight'), ('TRAIN', 'Train'), ('BUS', 'Bus')], max_length=10)),
                ('operator_name', models.CharField(max_length=200)),
                ('route_number', models.CharField(max_length=50)),
                ('source_city', models.CharField(max_length=100)),
                ('source_station', models.CharField(max_length=200)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_station', models.CharField(max_length=200)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration_hours', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('ac_available', models.BooleanField(default=False)),
                ('sleeper_available', models.BooleanField(default=False)),
                ('wifi_available', models.BooleanField(default=False)),
                ('food_service', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['departure_time', 'base_price'],
            },
        ),
        migrations.CreateModel(
            name='TransportBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField()),
                ('passengers', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('class_type', models.CharField(choices=[('ECONOMY', 'Economy'), ('PREMIUM', 'Premium'), ('BUSINESS', 'Business'), ('FIRST', 'First Class')], default='ECONOMY', max_length=10)),
                ('passenger_names', models.TextField()),
                ('passenger_ages', models.TextField()),
                ('passenger_genders', models.TextField()),
                ('price_per_ticket', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=17)),
                ('contact_email', models.EmailField(max_length=254)),
                ('booking_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=20)),
                ('booking_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('seat_numbers', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('punctuality_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comfort_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('service_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transportation.transportbooking')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'route')},
            },
        ),
    ]
