# Generated by Django 5.2.6 on 2025-09-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_sos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sosalert',
            old_name='contacts_notified',
            new_name='emails_sent',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='locationshare',
            name='shared_with_phone',
        ),
        migrations.RemoveField(
            model_name='sosalert',
            name='medical_notified',
        ),
        migrations.RemoveField(
            model_name='sosalert',
            name='police_notified',
        ),
        migrations.AddField(
            model_name='locationshare',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationshare',
            name='emails_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationshare',
            name='shared_with_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='safetycheckin',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safetycheckin',
            name='emails_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
